version: "3"

services:
  mysql:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: mysql
    environment:
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ..:/workspace
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql